---
- name: Create /opt/nso
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/opt/nso/releases"
    - "/opt/nso/run"
- name: Copy NSO
  copy:
    src: "nso-{{ nso_version }}.linux.x86_64.signed.bin"
    dest: "/opt/nso/releases"
    mode: '0755'
- name: Copy NEDs
  copy:
    src: "ncs-{{ nso_major_version }}-{{ item.name }}-{{ item.version }}.signed.bin"
    dest: "/opt/nso/releases"
    mode: '0755'
  with_items: "{{ nso_neds }}"
- name: Remove old NSO version
  file:
    path: "/opt/nso/releases/nso-{{ nso_version}}"
    state: absent
  ignore_errors: true
- name: Extract and Install NSO
  command:
    chdir: "/opt/nso/releases"
    cmd: "{{ item }}"
  with_items:
    - "/opt/nso/releases/nso-{{ nso_version }}.linux.x86_64.signed.bin"
    - "/opt/nso/releases/nso-{{ nso_version }}.linux.x86_64.installer.bin /opt/nso/releases/nso-{{ nso_version }}"
- name: Extract NEDs
  command:
    chdir: "/opt/nso/releases"
    cmd: "/opt/nso/releases/ncs-{{ nso_major_version }}-{{ item.name }}-{{ item.version }}.signed.bin"
  with_items: "{{ nso_neds }}"
# - name: Remove default NEDs
- name: Unpack NEDs
  unarchive:
    src: "/opt/nso/releases/ncs-{{ nso_major_version }}-{{ item.name }}-{{ item.version }}.tar.gz"
    dest: "/opt/nso/releases/nso-{{ nso_version }}/packages/neds/"
    remote_src: yes
    creates: "/opt/nso/releases/nso-{{ nso_version }}/packages/neds/{{ item.name }}-cli-{{ item.version }}"
  with_items: "{{ nso_neds }}"
- name: NEDs setup
  shell:
    cmd: |
      source /opt/nso/releases/nso-{{ nso_version }}/ncsrc
      /opt/nso/releases/nso-{{ nso_version }}/bin/ncs-setup --dest /opt/nso/run
- name: Make NEDs current symlink live
  file:
    src: "/opt/nso/releases/nso-{{ nso_version }}/packages/neds/{{ item.name }}-cli-{{ item.version | regex_replace('^([0-9]+\\.[0-9]+)(\\.[0-9]+)?$', '\\1') }}"
    dest: "/opt/nso/run/{{ item.name }}-cli-{{ item.version | regex_replace('^([0-9]+\\.[0-9]+)(\\.[0-9]+)?$', '\\1') }}"
    state: link
  with_items: "{{ nso_neds }}"
- name: Restart NEDs
  shell:
    chdir: "/opt/nso/run"
    cmd: "source /opt/nso/releases/nso-{{ nso_version }}/ncsrc; /opt/nso/releases/nso-{{ nso_version }}/bin/ncs --with-package-reload-force"
- name: Make NSO current symlink live
  file:
    src: "/opt/nso/releases/nso-{{ nso_version }}"
    dest: "/opt/nso/current"
    state: link
- name:
  debug:
    msg: "All Done.  Login with vagrant ssh then use ncs_cli -C -u admin to login to NSO"

